kind: pipeline
type: docker
name: test_pipeline

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

- name: build docker
  image: compose:1.23.2
  commands:
  - build .